//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.sorter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sorter.IWCFSorter")]
    public interface IWCFSorter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSorter/Sort", ReplyAction="http://tempuri.org/IWCFSorter/SortResponse")]
        int[] Sort(int[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSorter/Sort", ReplyAction="http://tempuri.org/IWCFSorter/SortResponse")]
        System.Threading.Tasks.Task<int[]> SortAsync(int[] array);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFSorterChannel : Client.sorter.IWCFSorter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFSorterClient : System.ServiceModel.ClientBase<Client.sorter.IWCFSorter>, Client.sorter.IWCFSorter {
        
        public WCFSorterClient() {
        }
        
        public WCFSorterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFSorterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSorterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSorterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] Sort(int[] array) {
            return base.Channel.Sort(array);
        }
        
        public System.Threading.Tasks.Task<int[]> SortAsync(int[] array) {
            return base.Channel.SortAsync(array);
        }
    }
}
